version: '3.7'
services:
  resume:
    build: .
    ports:
    - '3000:3000'
    - '35729:35729'
    volumes:
    - './src/index.js:/opt/app/src/index.js'
    - './src/resume.md:/opt/app/src/resume.md'

